(**
 **************************************************************************
 *                                                                        *
 *  This file is part of the uktat Developer's Component Library.        *
 *                                                                        *
 *  See the file COPYING.modifiedLGPL.txt, included in this distribution, *
 *  for details about the copyright.                                      *
 *                                                                        *
 *  This program is distributed in the hope that it will be useful,       *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                  *
 *                                                                        *
 **************************************************************************
**)

unit uktlangs;

interface
uses
  Classes, SysUtils,
  uktresLangs,
  dummy;

 // ISO 639 language codes

 // Note:
 // 1. "SpanishEurope"  added.
 // 2. "PortugueseEurope" added.
 // 3. "SpanishAmerica" added.
 // 4. "PortugueseBrasil" added.
 // 5. "JapaneseAynu" added.
 // 6. "None" added.

type

  TSDVLanguage =
  (
//    lgNone,
    lgNeutral,

    lgAfar,
    lgAbkhazian,
    lgAvestan,
    lgAfrikaans,
    lgAkan,
    lgAmharic,
    lgAragonese,
    lgArabic,
    lgAssamese,
    lgAvaric,
    lgAymara,
    lgAzerbaijani,
    lgBashkir,
    lgBelarusian,
    lgBulgarian,
    lgBihari,
    lgBislama,
    lgBambara,
    lgBengali,
    lgTibetan,
    lgBreton,
    lgBosnian,
    lgCatalan,
    lgChechen,
    lgChamorro,
    lgCorsican,
    lgCree,
    lgCzech,
    lgChuvash,
    lgWelsh,
    lgDanish,
    lgGerman,
    lgDivehi,
    lgDzongkha,
    lgEwe,
    lgGreek,
    lgEnglish,
    lgEnglishAmerican,
    lgEnglishBritish,
    lgEnglishAustralian,
    lgEsperanto,
    lgSpanish,
    lgEstonian,
    lgBasque,
    lgPersian,
    lgFulah,
    lgFinnish,
    lgFijian,
    lgFaroese,
    lgFrench,
    lgWalloonBelgique,
    lgFrisian,
    lgIrish,
    lgGaelic,
    lgGallegan,
    lgGuarani,
    lgGujarati,
    lgManx,
    lgHausa,
    lgHebrew,
    lgHindi,
    lgHiriMotu,
    lgCroatian,
    lgHaitian,
    lgHungarian,
    lgArmenian,
    lgHerero,
    lgInterlingua,
    lgIndonesian,
    lgInterlingue,
    lgIgbo,
    lgSichuanYi,
    lgInupiaq,
    lgIdo,
    lgIcelandic,
    lgItalian,
    lgInuktitut,
    lgJapanese,
    lgJavanese,
    lgGeorgian,
    lgKongo,
    lgKikuyu,
    lgKuanyama,
    lgKazakh,
    lgGreenlandic,
    lgKhmer,
    lgKannada,
    lgKorean,
    lgKanuri,
    lgKashmiri,
    lgKurdish,
    lgCornish,
    lgKomi,
    lgKirghiz,
    lgLatin,
    lgLuxembourgish,
    lgGanda,
    lgLimburgan,
    lgLingala,
    lgLao,
    lgLithuanian,
    lgLubaKatanga,
    lgLatvian,
    lgMalagasy,
    lgMarshallese,
    lgMaori,
    lgMacedonian,
    lgMalayalam,
    lgMongolian,
    lgMoldavian,
    lgMarathi,
    lgMalay,
    lgMaltese,
    lgBurmese,
    lgNauru,
    lgNorwegianBokmaal,
    lgNdebeleNorth,
    lgNepali,
    lgNdonga,
    lgDutch,
    lgFlemish,
    lgNorwegianNynorsk,
    lgNorwegian,
    lgNdebeleSouth,
    lgNavajo,
    lgChichewa,
    lgOccitan,
    lgOjibwa,
    lgOromo,
    lgOriya,
    lgOssetian,
    lgPanjabi,
    lgPali,
    lgPolish,
    lgPushto,
    lgPortuguese,
    lgQuechua,
    lgRaetoRomance,
    lgRundi,
    lgRomanian,
    lgRussian,
    lgKinyarwanda,
    lgSanskrit,
    lgSardinian,
    lgSindhi,
    lgNorthernSami,
    lgSango,
    lgSinhalese,
    lgSlovak,
    lgSlovenian,
    lgSamoan,
    lgShona,
    lgSomali,
    lgAlbanian,
    lgSerbian,
    lgSwati,
    lgSothoSouthern,
    lgSundanese,
    lgSwedish,
    lgSwahili,
    lgTamil,
    lgTelugu,
    lgTajik,
    lgThai,
    lgTigrinya,
    lgTurkmen,
    lgTagalog,
    lgTswana,
    lgTonga,
    lgTurkish,
    lgTsonga,
    lgTatar,
    lgTwi,
    lgTahitian,
    lgUighur,
    lgUkrainian,
    lgUrdu,
    lgUzbek,
    lgVenda,
    lgVietnamese,
    lgVolapuk,
    lgWalloon,
    lgWolof,
    lgXhosa,
    lgYiddish,
    lgYoruba,
    lgZhuang,
    lgChinese,
    lgZulu,

    lgSpanishEurope,
    lgSpanishAmerica,
    lgPortugueseEurope,
    lgPortugueseBrasil,
    lgJapaneseAynu
  );

  function SafeLang(const Value: TSDVLanguage): TSDVLanguage;

  function LangToStr(const Value: TSDVLanguage): string;
  function LangToText(const Value: TSDVLanguage): string;

  function StrToLang(const Value: string): TSDVLanguage;
  function TextToLang(const Value: string): TSDVLanguage;

implementation

type
  TLanguageNames = array[TSDVLanguage] of string;

const
  LangToStrArray: TLanguageNames =
  (
    strlgNeutral,
//    strlgNone,

    strlgAfar,
    strlgAbkhazian,
    strlgAvestan,
    strlgAfrikaans,
    strlgAkan,
    strlgAmharic,
    strlgAragonese,
    strlgArabic,
    strlgAssamese,
    strlgAvaric,
    strlgAymara,
    strlgAzerbaijani,
    strlgBashkir,
    strlgBelarusian,
    strlgBulgarian,
    strlgBihari,
    strlgBislama,
    strlgBambara,
    strlgBengali,
    strlgTibetan,
    strlgBreton,
    strlgBosnian,
    strlgCatalan,
    strlgChechen ,
    strlgChamorro,
    strlgCorsican,
    strlgCree,
    strlgCzech,
    strlgChuvash,
    strlgWelsh,
    strlgDanish,
    strlgGerman,
    strlgDivehi,
    strlgDzongkha,
    strlgEwe,
    strlgGreek,
    strlgEnglish,
    strlgEnglishAmerican,
    strlgEnglishBritish,
    strlgEnglishAustralian,
    strlgEsperanto,
    strlgSpanish,
    strlgEstonian,
    strlgBasque,
    strlgPersian,
    strlgFulah,
    strlgFinnish,
    strlgFijian,
    strlgFaroese,
    strlgFrench,
    strlgWalloonBelgique,
    strlgFrisian,
    strlgIrish,
    strlgGaelic,
    strlgGallegan,
    strlgGuarani,
    strlgGujarati,
    strlgManx,
    strlgHausa,
    strlgHebrew,
    strlgHindi,
    strlgHiriMotu,
    strlgCroatian,
    strlgHaitian,
    strlgHungarian,
    strlgArmenian,
    strlgHerero,
    strlgInterlingua,
    strlgIndonesian,
    strlgInterlingue,
    strlgIgbo,
    strlgSichuanYi,
    strlgInupiaq,
    strlgIdo,
    strlgIcelandic,
    strlgItalian,
    strlgInuktitut,
    strlgJapanese,
    strlgJavanese,
    strlgGeorgian,
    strlgKongo,
    strlgKikuyu,
    strlgKuanyama,
    strlgKazakh,
    strlgGreenlandic,
    strlgKhmer,
    strlgKannada,
    strlgKorean,
    strlgKanuri,
    strlgKashmiri,
    strlgKurdish,
    strlgCornish,
    strlgKomi,
    strlgKirghiz,
    strlgLatin,
    strlgLuxembourgish,
    strlgGanda,
    strlgLimburgan,
    strlgLingala,
    strlgLao,
    strlgLithuanian,
    strlgLubaKatanga,
    strlgLatvian,
    strlgMalagasy,
    strlgMarshallese,
    strlgMaori,
    strlgMacedonian,
    strlgMalayalam,
    strlgMongolian,
    strlgMoldavian,
    strlgMarathi,
    strlgMalay,
    strlgMaltese,
    strlgBurmese,
    strlgNauru,
    strlgNorwegianBokmaal,
    strlgNdebeleNorth,
    strlgNepali,
    strlgNdonga,
    strlgDutch,
    strlgFlemish,
    strlgNorwegianNynorsk,
    strlgNorwegian,
    strlgNdebeleSouth,
    strlgNavajo,
    strlgChichewa,
    strlgOccitan,
    strlgOjibwa,
    strlgOromo,
    strlgOriya,
    strlgOssetian,
    strlgPanjabi,
    strlgPali,
    strlgPolish ,
    strlgPushto,
    strlgPortuguese,
    strlgQuechua,
    strlgRaetoRomance,
    strlgRundi,
    strlgRomanian,
    strlgRussian,
    strlgKinyarwanda,
    strlgSanskrit,
    strlgSardinian,
    strlgSindhi,
    strlgNorthernSami,
    strlgSango,
    strlgSinhalese,
    strlgSlovak,
    strlgSlovenian,
    strlgSamoan,
    strlgShona,
    strlgSomali,
    strlgAlbanian,
    strlgSerbian,
    strlgSwati,
    strlgSothoSouthern,
    strlgSundanese,
    strlgSwedish,
    strlgSwahili,
    strlgTamil,
    strlgTelugu,
    strlgTajik,
    strlgThai,
    strlgTigrinya,
    strlgTurkmen,
    strlgTagalog,
    strlgTswana,
    strlgTonga,
    strlgTurkish,
    strlgTsonga,
    strlgTatar,
    strlgTwi,
    strlgTahitian,
    strlgUighur,
    strlgUkrainian,
    strlgUrdu,
    strlgUzbek,
    strlgVenda,
    strlgVietnamese,
    strlgVolapuk,
    strlgWalloon,
    strlgWolof,
    strlgXhosa,
    strlgYiddish,
    strlgYoruba,
    strlgZhuang,
    strlgChinese,
    strlgZulu,

    strlgSpanishEurope,
    strlgSpanishAmerica,
    strlgPortugueseEurope,
    strlgPortugueseBrasil,
    strlgJapaneseAynu
  );

  LangToTextArray: TLanguageNames =
  (
    textlgNeutral,
//    textlgNone,

    textlgAfar,
    textlgAbkhazian,
    textlgAvestan,
    textlgAfrikaans,
    textlgAkan,
    textlgAmharic,
    textlgAragonese,
    textlgArabic,
    textlgAssamese,
    textlgAvaric,
    textlgAymara,
    textlgAzerbaijani,
    textlgBashkir,
    textlgBelarusian,
    textlgBulgarian,
    textlgBihari,
    textlgBislama,
    textlgBambara,
    textlgBengali,
    textlgTibetan,
    textlgBreton,
    textlgBosnian,
    textlgCatalan,
    textlgChechen ,
    textlgChamorro,
    textlgCorsican,
    textlgCree,
    textlgCzech,
    textlgChuvash,
    textlgWelsh,
    textlgDanish,
    textlgGerman,
    textlgDivehi,
    textlgDzongkha,
    textlgEwe,
    textlgGreek,
    textlgEnglish,
    textlgEnglishAmerican,
    textlgEnglishBritish,
    textlgEnglishAustralian,
    textlgEsperanto,
    textlgSpanish,
    textlgEstonian,
    textlgBasque,
    textlgPersian,
    textlgFulah,
    textlgFinnish,
    textlgFijian,
    textlgFaroese,
    textlgFrench,
    textlgWalloonBelgique,
    textlgFrisian,
    textlgIrish,
    textlgGaelic,
    textlgGallegan,
    textlgGuarani,
    textlgGujarati,
    textlgManx,
    textlgHausa,
    textlgHebrew,
    textlgHindi,
    textlgHiriMotu,
    textlgCroatian,
    textlgHaitian,
    textlgHungarian,
    textlgArmenian,
    textlgHerero,
    textlgInterlingua,
    textlgIndonesian,
    textlgInterlingue,
    textlgIgbo,
    textlgSichuanYi,
    textlgInupiaq,
    textlgIdo,
    textlgIcelandic,
    textlgItalian,
    textlgInuktitut,
    textlgJapanese,
    textlgJavanese,
    textlgGeorgian,
    textlgKongo,
    textlgKikuyu,
    textlgKuanyama,
    textlgKazakh,
    textlgGreenlandic,
    textlgKhmer,
    textlgKannada,
    textlgKorean,
    textlgKanuri,
    textlgKashmiri,
    textlgKurdish,
    textlgCornish,
    textlgKomi,
    textlgKirghiz,
    textlgLatin,
    textlgLuxembourgish,
    textlgGanda,
    textlgLimburgan,
    textlgLingala,
    textlgLao,
    textlgLithuanian,
    textlgLubaKatanga,
    textlgLatvian,
    textlgMalagasy,
    textlgMarshallese,
    textlgMaori,
    textlgMacedonian,
    textlgMalayalam,
    textlgMongolian,
    textlgMoldavian,
    textlgMarathi,
    textlgMalay,
    textlgMaltese,
    textlgBurmese,
    textlgNauru,
    textlgNorwegianBokmaal,
    textlgNdebeleNorth,
    textlgNepali,
    textlgNdonga,
    textlgDutch,
    textlgFlemish,
    textlgNorwegianNynorsk,
    textlgNorwegian,
    textlgNdebeleSouth,
    textlgNavajo,
    textlgChichewa,
    textlgOccitan,
    textlgOjibwa,
    textlgOromo,
    textlgOriya,
    textlgOssetian,
    textlgPanjabi,
    textlgPali,
    textlgPolish ,
    textlgPushto,
    textlgPortuguese,
    textlgQuechua,
    textlgRaetoRomance,
    textlgRundi,
    textlgRomanian,
    textlgRussian,
    textlgKinyarwanda,
    textlgSanskrit,
    textlgSardinian,
    textlgSindhi,
    textlgNorthernSami,
    textlgSango,
    textlgSinhalese,
    textlgSlovak,
    textlgSlovenian,
    textlgSamoan,
    textlgShona,
    textlgSomali,
    textlgAlbanian,
    textlgSerbian,
    textlgSwati,
    textlgSothoSouthern,
    textlgSundanese,
    textlgSwedish,
    textlgSwahili,
    textlgTamil,
    textlgTelugu,
    textlgTajik,
    textlgThai,
    textlgTigrinya,
    textlgTurkmen,
    textlgTagalog,
    textlgTswana,
    textlgTonga,
    textlgTurkish,
    textlgTsonga,
    textlgTatar,
    textlgTwi,
    textlgTahitian,
    textlgUighur,
    textlgUkrainian,
    textlgUrdu,
    textlgUzbek,
    textlgVenda,
    textlgVietnamese,
    textlgVolapuk,
    textlgWalloon,
    textlgWolof,
    textlgXhosa,
    textlgYiddish,
    textlgYoruba,
    textlgZhuang,
    textlgChinese,
    textlgZulu,

    textlgSpanishEurope,
    textlgSpanishAmerica,
    textlgPortugueseEurope,
    textlgPortugueseBrasil,
    textlgJapaneseAynu
  );

function SafeLang(const Value: TSDVLanguage): TSDVLanguage;
begin
  Result := Value;
  if (Result < Low(TSDVLanguage))
    then Result := Low(TSDVLanguage);
  if (Result > High(TSDVLanguage))
    then Result := High(TSDVLanguage);
  // Goal: Checks that a language is valid.
  // Objetivo: Revisa que el lenguaje sea valido.
end;

function LangToStr(const Value: TSDVLanguage): string;
begin
  Result := LangToStrArray[Value];
  // Objetivo: Convertir un valor "language" a un valor "string".
  // Goal: To cast a "language" value to a "string" value.
end;

function LangToText(const Value: TSDVLanguage): string;
begin
  Result := LangToTextArray[Value];
  // Objetivo: Convertir un valor "language" a texto legible.
  // Goal: To cast a "language" value to a readable text.
end;

function MatchLanguage
  (const Value: string; const LanguageNames: TLanguageNames): TSDVLanguage;
var i: TSDVLanguage; Found: Boolean;
begin
  i := Low(TSDVLanguage); Found := FALSE;
  while ((i <= High(TSDVLanguage)) and (not Found)) do
  begin
    Found := SameText(LanguageNames[i], Value);
    Inc(i);
  end;

  if (Found)
    then Result := Pred(i)
    else Result := Low(TSDVLanguage);
  // Goal: Locates a language by its name in a given array.
end;

function StrToLang(const Value: string): TSDVLanguage;
begin
  Result := MatchLanguage(Value, LangToStrArray);
  // Goal: To cast a "string" value to a "Language" value.
  // Objetivo: Convertir un valor "string" a un valor "Language".
end;

function TextToLang(const Value: string): TSDVLanguage;
begin
  Result := MatchLanguage(Value, LangToTextArray);
  // Goal: To cast a "string" value to a "Language" value.
  // Objetivo: Convertir un valor "string" a un valor "Language".
end;

end.
